<template>
	<Navbar />
	<section class="project" :class="{ 'light-mode': !isDarkMode }">
		<section class="project-sec">
			<div class="title-con title-mod">
				<h2><span>/</span>Projects</h2>
				<p>List of my projects</p>
			</div>
			<div class="card-con">
				<Projectcard
					v-for="(project, index) in projects"
					:key="index"
					:project="project" />
			</div>
		</section>

		<section class="skills">
			<div class="title-con">
				<h2><span>#</span>Pet-project</h2>
				<div class="line"></div>
			</div>
			<section class="skills-con">
				<div class="skillcard">
					<div class="stacks">
						<p>JavaScript</p>
					</div>
					<div class="techs">
						<h3>Twilio-go-verify</h3>
						<p>
							A multi-factor authentication implementation for a Golang
							application using Twilio Verify services like Authy and SMS OTP.
						</p>
						<div class="resume">
							<a
								href="https://github.com/DesmondSanctity/twilio-go-verify"
								target="_blank">
								Github
								<div>
									<img src="../assets/icons/uil-link-h.png" alt="" />
								</div>
							</a>
						</div>
					</div>
				</div>
				<div class="skillcard">
					<div class="stacks">
						<p>Rust</p>
					</div>
					<div class="techs">
						<h3>Nike-taxi-rs</h3>
						<p>
							A leaderboard for a Rust learning group using the Rustlings
							exercise
						</p>
						<div class="resume">
							<a
								href="https://github.com/DesmondSanctity/nike-taxi-rs"
								target="_blank">
								Github
								<div>
									<img src="../assets/icons/uil-link-h.png" alt="" />
								</div>
							</a>
						</div>
					</div>
				</div>
				<div class="skillcard">
					<div class="stacks">
						<p>TypeScript</p>
					</div>
					<div class="techs">
						<h3>Ai-generated-blog-api</h3>
						<p>Blog API generated by OpenAI GPT 4o</p>
						<div class="resume">
							<a
								href="https://github.com/DesmondSanctity/ai-generated-blog-api"
								target="_blank">
								Github
								<div>
									<img src="../assets/icons/uil-link-h.png" alt="" />
								</div>
							</a>
						</div>
					</div>
				</div>
			</section>
		</section>
		<Footer />
	</section>
</template>

<script setup>
import Navbar from '../components/navbar.vue';
import Footer from '../components/footer.vue';
import Projectcard from '../components/projectcard.vue';
import { useTheme } from '../composables/useTheme';

const props = defineProps({
	project: Object,
});

const { isDarkMode } = useTheme();

import { ref } from 'vue';

const projects = ref([
	{
		title: ' Ai-summarizer',
		description:
			"AI tool that summarizes text from documents using VertexAI and/or Langchain's Open AI implementation ",
		technologies: ' JavaScript css',
		imageUrl: '/images/Cover(1).jpg',
		projectUrl: '#',
		githubUrl: 'https://github.com/DesmondSanctity/ai-summarizer',
	},
	{
		title: 'Tyche-nomisma',
		description:
			'An AI tool that you can use to get currency pair update via Whatsapp. Built with Twilio and Cloudflare Workers AI. ',
		technologies: 'JavaScript',
		imageUrl: '/images/currency.png',
		projectUrl: '#',
		githubUrl: 'https://github.com/DesmondSanctity/tyche-nomisma',
	},
	{
		title: ' Claude-functions',
		description:
			'Learn how to build and integrate AI agents into your application using the function calling feature. ',
		technologies: 'JavaScript',
		imageUrl: '/images/AI.png',
		projectUrl: '#',
		githubUrl: 'https://github.com/DesmondSanctity/claude-functions',
	},
]);
</script>

<style lang="scss" scoped>
@use '../styles/variables' as *;
@use '../styles/mixin' as *;

@include fadeIn;

.project {
	margin: 160px $body-margin 0;
	animation: fadeIn 1s ease-out forwards;

	@include macbookpro {
		margin: 160px $body-margin-macpro 0;
	}
	@include macbook {
		margin: 160px $body-margin-mac 0;
	}
	@include mobile {
		margin: 100px $body-margin-mobile 0;
	}

	@include tablet {
		margin: 150px $body-margin-tab 0;
	}

	.title-con {
		@include heading;
	}

	.title-mod {
		@include heading-mod;
	}

	.card-con {
		display: flex;
		justify-content: space-between;

		@include mobile {
			flex-direction: column;
			justify-content: center;
			align-items: center;
			gap: 32px;
		}

		@include tablet {
			flex-wrap: wrap;
			gap: 20px;
		}
	}

	.skills {
		margin: $body-margin-up 0;

		.skills-con {
			display: flex;
			justify-content: space-between;

			@include mobile {
				flex-direction: column;
				justify-content: center;
				align-items: center;
				gap: 32px;
			}
			@include tablet {
				flex-wrap: wrap;
				gap: 20px;
			}

			.skillcard {
				width: 355px;
				border: 1px solid $secondary-color;

				@include mobile {
					width: 100%;
				}

				@include macbook {
					width: 320px;
				}

				.stacks {
					padding: 15px 10px;
					border-bottom: 1px solid $secondary-color;

					p {
						font-family: Font5;
						font-size: $bodytxt;
						color: $secondary-color;
					}
				}

				.techs {
					padding: 16px;

					h3 {
						font-family: Font2;
						font-size: $subheading;
						color: $secondary-color;
						margin-bottom: 16px;

						@include tablet {
							margin-bottom: 10px;
						}
						
						@include mobile {
							font-size: $subheading-1;
						}
					}

					p {
						font-family: Font2;
						font-size: $bodytxt-2;
						color: $secondary-color;
						margin-bottom: 8px;

						@include macbook {
							font-size: $bodytxt-3;
						}
					}

					.resume {
						a {
							padding: 8px 16px;
							width: 110px;
							border: 1px solid $secondary-color-1;
							color: $secondary-color;
							font-family: Font2;
							font-size: $bodytxt-2;
							text-transform: capitalize;
							cursor: pointer;
							display: flex;
							gap: 10px;
							align-items: center;
							justify-content: center;
						}
					}
				}
			}
		}
	}

	&.light-mode {
		.project-sec,
		.skills {
			.title-con h2 {
				color: var(--text-black);
			}
		}

		.skills {
			.skills-con .skillcard {
				border-color: var(--text-black);
			}
			.skills-con .skillcard .stacks {
				border-color: var(--text-black);
			}
			.skills-con .skillcard .techs h3 {
				color: $secondary-color-1;
			}
			.skills-con .skillcard .techs p {
				color: var(--text-black);
			}
			.skills-con .skillcard .techs a {
				color: var(--text-black);
				border-color: var(--text-black);
			}
			.skills-con .skillcard .stacks p {
				color: var(--text-black);
			}
		}
	}
}
</style>
